### ISSUE TITLE
Package doesn't exist?

### ISSUE THREAD

**Issue by sschooler** [flr/FLife#6]
Hi,
The package doesn't exist for download.

**Comment by iagomosqueira** [comment]
The package source code is in this repository, from which you can install using, for example

```
devtools;:install_github("flr/FLife")
```

Compiled packages for windows are available at the FLR repository,

```
 install.packages(repos="http://flr-project.org/R") 
```

which exists as a github repository too, so

https://github.com/flr/R/blob/master/bin/windows/contrib/4.1/FLife_3.4.0.zip

has the windows binary package for R 4.1.

Info on installation and some tutorials are available at <https://flr-project.org/>

Happy FLifing ...

**Comment by sschooler** [comment]
I was looking here : https://github.com/flr/FLife/releases/, which is the link from the website, just FYI.Additionally, I couldn’t find it in the repository either in R. From: Iago MosqueiraSent: Wednesday, November 10, 2021 3:50 PMTo: flr/FLifeCc: sschooler; AuthorSubject: Re: [flr/FLife] Package doesn't exist? (Issue #6) The package source code is in this repository, from which you can install using, for exampledevtools;:install_github("flr/FLife")Compiled packages for windows are available at the FLR repository, install.packages(repos="http://flr-project.org/R") which exists as a github repository too, sohttps://github.com/flr/R/blob/master/bin/windows/contrib/4.1/FLife_3.4.0.ziphas the windows binary package for R 4.1.Info on installation and some tutorials are available at https://flr-project.org/Happy FLifing ...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iagomosqueira** [comment]
Yes, FLR packages are not currently in CRAN.
